### ISSUE TITLE
Auto-restore based on CWD

### ISSUE THREAD

**Issue by FormalSnake** [jedrzejboczar/possession.nvim#45] opened 2023-11-14 20:02 UTC
It loads sessions from other directories and it is very annoying. I created a keybind that loads the session aswell. This should use the sessions corresponding to the directory and not one big session file (I think that is what it does)

```lua
require('possession').setup {
	commands = {
		save = 'SSave',
		load = 'SLoad',
		delete = 'SDelete',
		list = 'SList',
	},
	autosave = {
		current = true,
		tmp = true,
		on_load = true,
		on_quit = true,
	},
}

```

**Comment by jedrzejboczar** [comment] 2023-11-18 18:43
Currently there is no auto-restoring of sessions per directory. I believe this is a duplicate of https://github.com/jedrzejboczar/possession.nvim/issues/3?

**Comment by FormalSnake** [comment] 2023-11-18 19:01
I did not come across that issue when searching. But it seems that the issue was never resolved

**Comment by jedrzejboczar** [comment] 2023-11-18 19:07
Yeah, this is yet on the TODO list. When I find some more time I might add this. Or if anyone want to give it a go then feel free. Some notes:
* config option to enable this
* config option to control restoring from parent dirs (should we load `/a/b` from `/a/b/c`)
* config option to control if loading happens without confirmation or using vim.ui.input/vim.ui.select
* should we also restore after `DirChanged` autocmd?

**Comment by jedrzejboczar** [comment] 2024-06-11 09:03
Implemented in https://github.com/jedrzejboczar/possession.nvim/pull/55.

**Closed by jedrzejboczar** 2024-06-11 09:03 UTC
